About = "About"
AboutContent = "# Introduce \n\n Fetch Github Hosts is a Github Hosts synchronization tool primarily designed to address \n\n issues such as slow access to Github or other issues for researchers and learners\n---\n# License\nGNU General Public License v3.0\n\n# Version"
CheckUpdate = "Update Check"
CheckUpdateFail = "Check for updates failed"
CleanGithubHostsFail = "Clearing github records in hosts failed"
CleanGithubHostsSuccess = "The github record in the hosts file has been successfully cleared"
ClearHosts = "Clear hosts"
ClientFetchHostsGetErrorLog = "Failed to obtain the latest hosts"
ClientFetchHostsReadErrorLog = "Failed to read the latest hosts"
ClientMode = "Client Mode"
CurrentIsNewest = "Currently, it is the latest version"
DownloadNow = "Download Now"
Feedback = "Feedback"
FetchGithubHostsFail = "Failed to obtain the Host for Github"
GetHostRecordErr = "Failed to obtain host records"
GetIntervalMinutes = "Get interval (minutes)"
GetIntervalNeedInt = "Get interval must be an integer"
HostsOptCustom = "Custom hosts source"
HostsOptOfficial = "Official designated hosts source"
HostsOrigin = "Hosts origin"
ListeningAddress = "Listening address {{.Addr}}"
ListeningAddressWait = "Listening address: To be started"
LogCreatedFail = "Log file creation failed"
NetworkRequestFail = "Network request error"
Ok = "OK"
OpenHome = "Open home"
ParseDomainsJsonErr = "domain.json parsing failed"
ParseUpdateResponseFail = "Failed to parse and update response content"
PortMustBeInt = "Port number must be an integer"
ReadDomainsJsonErr = "Error reading file domains.json"
ReadHostsErr = "Error reading file hosts"
ReadIndexFileErr = "Failed to read homepage template file"
ReadUpdateResponseFail = "Failed to read update response content"
RemoteHostsFetchErrorLog = "Failed to update Github Hosts: {{.E}}"
RemoteHostsFetchStopLog = "Stop obtaining hosts"
RemoteHostsFetchSuccessLog = "Successfully updated Github Hosts!"
RemoteHostsUrl = "Remote hosts url"
RemoteHostsUrlLog = "Remote hosts obtaining links: {{.Url}}"
RequestFail = "request failure"
ServerFetchHostsErrorLog = "Failed to execute update Github Hosts: {{.E}}"
ServerFetchHostsStopErrorLog = "Failed to close port listening"
ServerFetchHostsStopLog = "Stopping updating hosts service"
ServerFetchHostsStopSuccessLog = "Stopped updating hosts service"
ServerFetchHostsSuccessLog = "Successfully executed update Github Hosts!"
ServerFetchIndexFileErr = "Failed to retrieve homepage file: {{.E}}"
ServerMode = "Server Mode"
ServerStartErrorLog = "Service startup failed (possibly due to the target port being occupied): {{.E}}"
ServerStartSuccessHostsJsonLinkLog = "JSON format link for hosts: http://127.0.0.1:{{.Port}}/hosts.json"
ServerStartSuccessHostsLinkLog = "Hosts file link: http://127.0.0.1:{{.Port}}/hosts.txt"
ServerStartSuccessLog = "Successfully listened to HTTP service:http://127.0.0.1:{{.Port}}"
Start = "Start"
StartupAutoGet = "Startup auto start"
StartupAutoGetTips = "The automatic acquisition status of the startup software has changed and will take effect the next time the program is launched!"
StartupPort = "Start port"
Stop = "Stop"
Tip = "Tip"
UpdateLater = "Update later"
UpdateTip = "Update Tip"
UpdateTipContent = "Detected a new version, do you need to download the latest version immediately?"
VersionParseFail = "Version number parsing failed"
WriteHostsJsonFileErr = "Writing data to the hosts.json file failed"
WriteHostsNoPermission = "Writing hosts file failed, please start this program as a super administrator!"
WriteHostsTxtFileErr = "Writing data to the hosts.txt file failed"
WriteIndexFileErr = "Failed to write update information to the homepage file"
